### ISSUE TITLE
Unhandled error: Sequence contains more than one element

### ISSUE THREAD

**Issue by buckstephenh** [Hubert-Rybak/DotnetPack#28]
Running Publish...
Unhandled error: Sequence contains more than one element

No other information available to understand the failure.

**Comment by Hubert-Rybak** [comment]
Could you post an output you get with -v (verbose) flag?

**Comment by tgjones** [comment]
I'm getting the same issue. Here's the stack trace:

```
Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at DotnetWarp.Context.FindAssemblyName() in C:\DEV\dotnet-warp\src\dotnet-warp\Context.cs:line 67
   at DotnetWarp.CmdCommands.DotnetCli.Publish(Context context, DotnetPublishOptions dotnetPublishOptions) in C:\DEV\dotnet-warp\src\dotnet-warp\CmdCommands\DotnetCli.cs:line 52
   at DotnetWarp.Program.RunActions(IEnumerable`1 actions, Context ctx) in C:\DEV\dotnet-warp\src\dotnet-warp\Program.cs:line 122
   at DotnetWarp.Program.OnExecute() in C:\DEV\dotnet-warp\src\dotnet-warp\Program.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass138_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at DotnetWarp.Program.Main(String[] args) in C:\DEV\dotnet-warp\src\dotnet-warp\Program.cs:line 16
```

**Comment by tgjones** [comment]
I think it's related to setting `<PublishSingleFile>true</PublishSingleFile>` in the csproj. With this set, there is no `deps.json` in the temp folder.

**Comment by Hubert-Rybak** [comment]
Are you using .NET Core 3.0? PublishSingleFile makes single file deployment already, which is new in 3.0, so you don't have to use this tool.

**Comment by tgjones** [comment]
I am using .NET Core 3.0. But with `PublishSingleFile` and `PublishTrimmed` both enabled, my resulting .exe size was 70Mb. With `dotnet warp`, it comes down to 20Mb, which is awesome (thank you!).

I removed `PublishSingleFile` from my .csproj and it works fine.
